<?php
session_start();
date_default_timezone_set("America/Lima");
/*define('DB_HOST','SRV-IND-AP01\SQLEXPRESS');
define('DB_USER','kunaq');
define('DB_PASS','kunaq2019');
define('DB_NAME','BDUS_INTRANET');*/
define('DB_HOST','kunaqfactelec.cgjpxdkt8txc.sa-east-1.rds.amazonaws.com');
define('DB_USER','sa_admin');
define('DB_PASS','asociados517');
define('DB_NAME','BDUS_INTRANET');